---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

## Stochastic model - Gillespie's algorithm
### SEPIAR model 
#### Initial conditions

```{r}
# devtools::install()
devtools::load_all()
R0 <- 1.2
params <- c(beta = R0/5, epsilon = 1/2.5, delta = 1/5, 
            gamma = 1/2.5, rho_p = 1, 
            rho_a = 1, frac_a = 0.3, frac_detect = 1)
y0 <- c(S = 1e7, E = 0, P = 0, A = 0, I = 10, R = 0, CE = 0, CI = 10)
tend <- 175
```

#### Run the ODE version of SEPAIR model
```{r}
times <- seq(0, tend, by = 1) # daily output for 150 days
library(deSolve)
library(tidyverse)
ode(y = y0, times = times, func = ode_sepair, parms = params) %>% 
  as.data.frame() -> out 

out$daily_infected <- c(0, diff(out$CE)) 
out$daily_symptom_onset <- c(0, diff(out$CI)) 
out$daily_confirmed <- c(0, diff(out$R))

tstamp <- format(Sys.time(), "%Y%m%dT%H%M%S")
daily_ode <- list()
daily_ode$daily_infected <- c(0, diff(out$CE)) 
daily_ode$daily_symptom_onset <- c(0, diff(out$CI)) 
daily_ode$daily_confirmed <- c(0, diff(out$R))
# saveRDS(daily_ode, paste0("outputs/daily_ode_", tstamp, ".rds"))

Rt <- rep(NA, length(times))
for (i in seq_along(times)){
  Rt[i] <- get_Rt(times[i])  
}
out <- cbind(out, Rt)

out_long <- out %>% pivot_longer(-time) 
out_long$name <- factor(out_long$name,
                        levels = c("S", "E", "P", "A", "I", "R", 
                                  "CE", "CI", "daily_infected", 
                                  "daily_symptom_onset", "daily_confirmed", "Rt"))
out_long %>% 
  filter(name == "daily_infected" | 
           name == "daily_symptom_onset" | name == "daily_confirmed") %>%
  ggplot(aes(x = time, y = value, color = name)) +
  geom_line(size = 1.2) +
  labs(x='Time (day)', y = 'Number of individuals', color = "") + 
  theme_grey(base_size = 16) 
  # facet_wrap(vars(name), nrow = 2, scales = "free_y")

```

## run model implemented in Gillespie's direct method
```{r}
set.seed(1)
tstart <- Sys.time()
nrun <- 100
res <- gillespie_run(func = gillespie_sepair, 
                     tend = tend, 
                     nrun = nrun, 
                     y0 = y0, 
                     params = params, 
                     report_dt = 1)
Sys.time() - tstart

daily_inf <- data.frame(matrix(0, nrow = tend + 1, ncol = nrun))
daily_ons <- data.frame(matrix(0, nrow = tend + 1, ncol = nrun))
daily_con <- data.frame(matrix(0, nrow = tend + 1, ncol = nrun))

for (i in seq_len(length(res))) {
  inf <- diff(res[[i]]$CE)
  onset <- diff(res[[i]]$CI)
  conf <- diff(res[[i]]$R)
  daily_inf[1:(length(inf)+1), i] <- c(0, inf)
  daily_ons[1:(length(onset)+1), i] <- c(0, onset)
  daily_con[1:(length(conf)+1), i] <- c(0, conf)
}

df <- daily_inf
df$time <- 0:tend
df %>% pivot_longer(cols = -time) -> df

ggplot() +
  geom_line(data = df, aes(time, value, group = name), 
            color = "grey50") +
  geom_line(data = out, mapping = aes(time, daily_infected), color = "darkred",
            size = 2, inherit.aes = FALSE)

daily_stoch <- list()
daily_stoch$confirmed <- daily_con
daily_stoch$onset <- daily_ons
daily_stoch$infected <- daily_inf

# saveRDS(daily_stoch, paste0("outputs/daily_stoch_", tstamp, ".rds"))
```

### Apply a detection rate
```{r}
rr <- nrow(daily_stoch$confirmed)
cc <- ncol(daily_stoch$confirmed)
detected <- data.frame(matrix(0, nrow = rr, ncol = cc))
daily_stoch_partial_obs <- list()
probs <- seq(0.2,0.8,0.1)
daily_stoch_partial_obs$probs <- probs
set.seed(30)
for (k in 1:length(probs)) {
  prob <- probs[k]
  for (i in 1:rr) {
     for (j in 1:cc){
       size <- daily_stoch$confirmed[i, j]
       # message(paste0("i = ", i, ", j = ", j, ", case = ", size, "\n"))
       if (!is.na(size) & size > 0){
         detected[i, j] <- rbinom(1, size = size, prob = prob)
       }
    }
  }
  daily_stoch_partial_obs$detected[[k]] <- detected
}

# saveRDS(daily_stoch_partial_obs, paste0("outputs/daily_stoch_partial_obs_", tstamp, ".rds"))
```
## total dataset
```{r}
Rt_dataset <- list()
Rt_dataset$ode <- daily_ode
Rt_dataset$stoch_perfect_obs <- daily_stoch
Rt_dataset$stoch_partial_obs <- daily_stoch_partial_obs
# saveRDS(Rt_dataset, paste0("outputs/Rt_dataset_", tstamp, ".rds"))
```


```{r}
library(Kmisc)
Rt <- sapply(1:101, function(x) get_Rt(x))
dat <- readRDS("outputs/Rt_data_set.rds")
library(pfilter)
params <- c(beta = R0/5, epsilon = 1/2.5, delta = 1/5, 
            gamma = 1/2.5, rho_p = 1, 
            rho_a = 1, frac_a = 0.3, frac_detect = 1)

## particle filter function has S, E, P, A, I, R, CE, CI, CR variables!!
y0 <- c(S = 1e7, E = 0, P = 0, A = 0, I = 10, R = 0, CE = 0, CI = 10, CR = 0)
tend <- 175
parnames <- c("epsilon", "delta", "gamma", "rho_p", "rho_a", "frac_a")
for (pn in parnames){
  theta[[pn]] <- params[[pn]]
}
usethis::use_data(theta, overwrite = T)

theta["betavol"] <- 0.4
devtools::load_all(".")

d <- data.frame(date = 1:101, daily_confirmed = round(dat$ode_perfect_obs$daily_confirmed))
d <- data.frame(date = 1:101, daily_infected = round(dat$ode_perfect_obs$daily_infected))

pf <- particle_filter(
  params = theta,
  y = y0,
  beta0 = 0.24,
  data = d,
  data_type = "infection",
  npart = 10000,
  tend = nrow(d),
  dt = 0.1,
  error_pdf = "pois",
  systematic_resampling = FALSE,
  filter_traj = TRUE, 
  stoch = FALSE)

plot(Rt, type="l")
med <- apply(pf$beta_filtered, 1, quantile, probs = c(0.5))
lower <- apply(pf$beta_filtered, 1, quantile, probs = c(0.025))
upper <- apply(pf$beta_filtered, 1, quantile, probs = c(0.975))
lines(med*5, lwd=2, col=3)
lines(upper*5, lty=2, lwd=2, col=3)
lines(lower*5, lty=2, lwd=2, col=3)
 
# devtools::install()
library(parallel)
library(doParallel)
library(foreach)
set.seed(23)
ncores <- detectCores()
cl <- makeCluster(getOption("cl.cores", ncores - 2))
doParallel::registerDoParallel(cl)

theta["betavol"] <- 0.6

pf <- foreach(i = 1:1e3, .packages = "pfilter", .inorder = F) %dopar% {
  extract_trace(params = theta,
                y = y0,
                data = d,
                data_type = "",
                npart = 1e4,
                tend = nrow(d),
                dt = 0.1,
                error_pdf = "pois",
                negbin_size = 30,
                stoch = FALSE)
}
parallel::stopCluster(cl)

pr <- c(0.025, 0.25, 0.5, 0.75, 0.975)
Rt_est <- as.data.frame(sapply(pf, function(x) x[, "Rt"]))
Rt_quantile <- as.data.frame(t(apply(Rt_est, 1, function(x) quantile(x, pr))))

df <- cbind(Rt_quantile, d[, c("date", "daily_infected")])
df$Rt <- Rt  
ggplot(df, aes(x = date)) +
  geom_ribbon(aes(ymin = `2.5%`, ymax = `97.5%`), fill = "steelblue", alpha = 0.4) +
  geom_ribbon(aes(ymin = `25%`, ymax = `75%`), fill = "steelblue", alpha = 0.6) +
  geom_line(aes(y = `50%`), color = "steelblue", size = 1) +
  geom_line(aes(y = Rt), size = 2) +
  geom_hline(yintercept = 1, color = "darkred", size = 1, linetype = "dotted")+
  labs(title = expression(R[t]~estimated~using~particle~filtering),
         y = expression(R[t]), x = "") 
  

```
